### ISSUE TITLE
Does not work on remote systems.

### ISSUE THREAD

**Issue by duaneking** [lepture/example-oauth2-server#33]
The examples gave me hope early on but they do not work when running on different host systems using domain names based on my tests on AWS Elastic Beanstalk instances.

**Comment by lepture** [comment]
@duaneking I can't figure out what's wrong with your issue description. I think it's just a complain rather than bug reporting.

FYI, Authlib is going to replace Flask-OAuthlib. Here is the documentation for implementing OAuth 2 server with Authlib in Flask: https://docs.authlib.org/en/latest/flask/oauth2.html
